version: '3.3'
services:
  db:
    image: 'mariadb:latest'
    restart: always
    environment:
      MYSQL_DATABASE: 'xss'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'FvzZ0a1mxfWWRp9gAeml'
      MYSQL_ROOT_PASSWORD: 'CAcZeESTUDeK4JSBrxlq'
  web:
    build: .
    depends_on: 
      - 'db'
    ports:
     - "8888:80"
    restart: always
    environment: 
      DATABASE_URL: 'mysql://user:FvzZ0a1mxfWWRp9gAeml@db/xss'
