version: "3.3"

secrets:
  db_password:
    file: ./.db_password

services:
  database:
    image: postgres:14.0-alpine3.14
    restart: unless-stopped
    secrets:
      - db_password
    environment:
      POSTGRES_DB: xss
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - xss-db:/var/lib/postgresql/data

  backend:
    build:
      context: "."
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    secrets:
      - db_password
    environment:
      POSTGRES_DB: xss
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_HOSTNAME: database
    depends_on:
      - database

  web:
    build:
      context: "."
      dockerfile: Dockerfile.web
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  xss-db:
