version: '3.3'
services:
  db:
    image: 'mariadb:latest'
    restart: 'unless-stopped'
    environment:
      MYSQL_DATABASE: 'xss'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'FvzZ0a1mxfWWRp9gAeml'
      MYSQL_ROOT_PASSWORD: 'CAcZeESTUDeK4JSBrxlq'
    volumes:
      - 'xss-db:/var/lib/mysql'

  backend: 
    build:
      context: '.'
      dockerfile: 'Dockerfile.backend'
    depends_on:
      - "db"
    restart: 'unless-stopped'
    environment:
      DATABASE_URL: 'mysql://user:FvzZ0a1mxfWWRp9gAeml@db/xss'
    command: [ "./wait-for-it.sh", "-t", "0", "db:3306", "--", "./startup.sh" ]

  frontend:
    build:
      context: '.'
      dockerfile: 'Dockerfile.frontend'
    depends_on: 
      - 'backend'
    ports:
     - '8888:80'
    restart: 'unless-stopped'
    command: [ "/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

volumes: 
  xss-db:

